import:
  - ~/.config/bspwm/alacritty/colors.yml

env:
  TERM: xterm-256color

window:
  opacity: 1
  padding:
    x: 30
    y: 20

    dynamic_padding: false

font:
  normal:
    family: SAGA

  bold:
    family: SAGA
    style: Regular

  italic:
    family: SAGA

  bold_italic:
    family: SAGA

  size: 13

live_config_reload: true

cursor:
  style: Beam
  vi_style_cursor: Beam
