#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

picom --experimental-backends --animations --config ~/.config/bspwm/picom/picom.conf &
feh --bg-fill ~/.config/bspwm/wallpapers/CatppuccinOrbit.png &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

polybar -c ~/.config/bspwm/polybar/config.ini mainbar0 &

bspc monitor -d I II III IV V 

bspc config border_width         3
bspc config window_gap          12

bspc config focused_border_color \#89dceb

bspc config top_padding 90
bspc config bottom_padding 90
bspc config left_padding 90
bspc config right_padding 90
